// src/constants/dares.ts
export const INITIAL_DARES: string[] = [
  "Take 1 sip",
  "Take 2 sips",
  "Take 3 sips",
  "Take a big gulp",
  "Finish your drink!",
  "Sip with non-dominant hand",
  "Drink with eyes closed",
  "Take 2 sips without using hands",
  "Drink while holding your nose",
  "Take 3 slow sips",
  "Chug for 3 seconds",
  "Drink while counting backward from 10",
  "Take 2 sips and shout 'Cheers!'",
  "Drink while standing on one leg",
  "Take 1 sip for each person wearing black",
  "Drink if you've ever lied on a dare",
  "Everyone drinks except you",
  "Trade drinks with someone and sip",
  "Pour a little of your drink into someone else's",
  "Drink while someone else holds your glass",
  "Take 2 sips and wink at someone",
  "Name a drink and sip it",
  "Take a shot if you’re the youngest",
  "Cheers with your neighbor and drink",
  "Drink while looking into someone’s eyes",
  "Take a sip for every ex you have",
  "Take a sip if you're single",
  "Take 1 sip if you’re taken",
  "Make a toast and take a sip",
  "Take 3 sips if you've ever ghosted someone",
  "SKIP your next turn",
  "SKIP: All players drink except you",
  "SKIP: Choose someone to skip their turn",
  "SKIP: Reverse order and take 1 sip",
  "SKIP: Next player drinks twice",
  "SKIP: Nominate someone to finish their drink",
  "Take 2 sips and point to a random player to drink",
  "Take 1 sip, then assign 3 sips to someone else",
  "Take 2 sips if your drink is darker than your neighbor’s",
  "Take 3 sips and ask someone a yes/no question",
  "Sip for every letter in your name",
  "Sip while spinning once",
  "Pass your drink, and take a sip from theirs",
  "Sip and give someone a compliment",
  "Take 1 sip per person wearing white",
  "Take 2 sips and do a toast",
  "Sip like you’re royalty",
  "Chug half your drink (or max 5 seconds)",
  "Take 3 sips for your last mistake",
  "Take 1 sip and choose someone to drink twice",
  "Take 2 sips while staring at someone",
  "Sip while balancing your glass on one finger",
  "Sip and say something you’ve never done",
  "Sip while patting your head",
  "Take a shot with your opposite hand",
  "Drink for every emoji in your last text",
  "Sip if you’ve ever lied about being drunk",
  "Take 1 sip for every social media app you have",
  "Take 2 sips and hum a song",
  "Take a sip and say a guilty pleasure",
  "Take 2 sips if you've ever DM'd your ex",
  "Sip while someone counts to 5",
  "Take 3 sips and smile for 10 seconds",
  "Sip if you’ve double texted",
  "Take a big gulp if you're the tallest",
  "Take 1 sip if you’re wearing black socks",
  "Drink and make eye contact with someone",
  "Take a sip and say who you’d switch drinks with",
  "Finish your drink if you’re the loudest in the group",
  "Take 2 sips while someone sings for you",
  "Take 1 sip for every ring or bracelet you wear",
  "Take 3 sips and tap someone’s head",
  "Sip if you’re using your phone right now",
  "Assign 2 sips to someone who’s laughing",
  "Take 1 sip and describe your drink",
  "Drink if your phone battery is below 50%",
  "Take 2 sips while acting serious",
  "Sip if you’ve ever lied today",
  "Take a big gulp if you’ve ever lost your phone",
  "Chug for 3 seconds if you’ve been ghosted",
  "Take 1 sip for every unread notification",
  "Take 2 sips if you’ve taken a selfie today",
  "Sip while blinking fast",
  "Take 3 sips if your last photo is a selfie",
  "Take a sip while doing nothing with your hands",
  "Drink while humming your favorite song",
  "Sip if you’re thinking of someone",
  "Take 1 sip and say your favorite drink",
  "Assign a shot to someone else",
  "Take 2 sips and say a pickup line",
  "Finish your drink if you’re sitting at the edge",
  "Take 1 sip and tell a drinking rule",
  "Drink with your left hand only",
  "Take 2 sips and do nothing else",
  "Take a shot if this is your first drink of the day",
  "SKIP: Take no sip but everyone else drinks",
  "SKIP: Close your eyes and skip your next two turns",
  "Take 1 sip for every button on your shirt",
  "Take 3 sips and make a toast",
  "Take 2 sips and say “Bottoms up!”"
];

export const BOARD_SIZE = 100; // 10x10 board
